name: CI
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches:
      - '**'
  schedule:
    - cron: '0 0 * * 0'
jobs:

  docker-build:
    name: Docker Build
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
          fetch-depth: 0
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
        with:
          install: false
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "mmore500/conduit:GITHUB_ACTION_${{ github.run_number }}"

  tidy:
    name: Docs, Miscellaneous
    runs-on: ubuntu-16.04
    needs:
      - docker-build
    steps:
      - uses: docker-practice/actions-setup-docker@v1
      - run: docker run "mmore500/conduit:GITHUB_ACTION_${{ github.run_number }}" /bin/bash -c "cd /opt/conduit && ./ci/test_tidy.sh"


  unit:
    name: Unit Tests
    runs-on: ubuntu-16.04
    needs:
      - docker-build
    strategy:
      matrix:
        mpicxx: [mpich, openmpi]
        mode: [ debug, fulldebug, opt ]
    env:
      UIT_MPICXX: mpicxx.${{ matrix.mpicxx }}
      UIT_MPIEXEC: mpicxx.${{ matrix.mpicxx }}
    steps:
      - uses: docker-practice/actions-setup-docker@v1
      - run: docker run -e UIT_MPICXX=$UIT_MPICXX -e UIT_MPIEXEC=$UIT_MPIEXEC "mmore500/conduit:GITHUB_ACTION_${{ github.run_number }}" /bin/bash -c "cd /opt/conduit/tests/ && make ${{ matrix.mpicxx }}"

  coverage:
    name: Coverage
    runs-on: ubuntu-16.04
    needs:
      - docker-build
    env:
      DISH_MPICXX: mpicxx.openmpi
      OMPI_CXX: clang++
    steps:
      - uses: docker-practice/actions-setup-docker@v1
      - run: export ci_env=`bash <(curl -s https://codecov.io/env)`
      - run: docker run $ci_env -e DISH_MPICXX=$DISH_MPICXX -e OMPI_CXX=$OMPI_CXX "mmore500/conduit:GITHUB_ACTION_${{ github.run_number }}" /bin/bash -c "cd /opt/condit/tests && make cov && bash <(curl -s https://codecov.io/bash)"

  microbenchmarks:
    name: Microbenchmarks
    runs-on: ubuntu-16.04
    needs:
      - docker-build
    steps:
      - uses: docker-practice/actions-setup-docker@v1
      - run: docker run -e OSF_USERNAME=${{ secrets.OSF_USERNAME }} -e OSF_PASSWORD=${{ secrets.OSF_PASSWORD }} -e CONTEXT=actions "mmore500/conduit:GITHUB_ACTION_${{ github.run_number }}" /bin/bash -c "cd /opt/conduit/microbenchmarks && make"

  macrobenchmarks:
    name: Macrobenchmarks
    runs-on: ubuntu-16.04
    needs:
      - docker-build
    steps:
      - uses: docker-practice/actions-setup-docker@v1
      - run: docker run -e OSF_USERNAME=${{ secrets.OSF_USERNAME }} -e OSF_PASSWORD=${{ secrets.OSF_PASSWORD }} -e CONTEXT=actions "mmore500/conduit:GITHUB_ACTION_${{ github.run_number }}" /bin/bash -c "cd /opt/conduit/macrobenchmarks && make"

  docs:
    name: Source, Docs, Demos
    runs-on: ubuntu-16.04
    needs:
      - docker-build
    steps:
      - uses: docker-practice/actions-setup-docker@v1
      - run: docker run --cap-add=SYS_ADMIN "mmore500/conduit:GITHUB_ACTION_${{ github.run_number }}" /bin/bash -c "cd /opt/conduit && make test-source && make docs && make demos"

  deploy-pages:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-16.04
    if: github.ref == 'refs/heads/master'
    needs:
      - docs
      - unit
      - coverage
      - macrobenchmarks
      - microbenchmarks
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - run:
        |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          echo $(cd third-party && ./install_emsdk.sh)
      - run: make web
      - run:
        |
          cd web
          git init
          git remote add origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/devosoft/empirical-prefab-demo.git > /dev/null 2>&1
          git checkout -b gh-pages
          git add .
          git commit --message "GitHub Run ${{ github.run_number }}"
          git push --force --quiet origin gh-pages

  deploy-dockerhub:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-16.04
    if: github.ref == 'refs/heads/master'
    needs:
      - docs
      - unit
      - coverage
      - macrobenchmarks
      - microbenchmarks

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: "mmore500/conduit:latest"
